apiVersion: v1
kind: Secret
metadata:
  name: {{ include "avatar-web.fullname" . }}
  labels:
    {{- include "avatar-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "avatar-web.databaseUrl" . }}
  DATABASE_PASSWORD: {{ .Values.postgresql.password | required "postgresql.password is required" | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | required "jwt.secret is required" | quote }}
  {{- if .Values.jwt.rsaPrivateKey }}
  JWT_PRIVATE_KEY: {{ .Values.jwt.rsaPrivateKey | quote }}
  {{- end }}
  {{- if .Values.jwt.rsaPublicKey }}
  JWT_PUBLIC_KEY: {{ .Values.jwt.rsaPublicKey | quote }}
  {{- end }}
  {{- if .Values.config.redisPassword }}
  REDIS_PASSWORD: {{ .Values.config.redisPassword | quote }}
  {{- end }}
  {{- if .Values.config.storageAccessKey }}
  STORAGE_ACCESS_KEY: {{ .Values.config.storageAccessKey | quote }}
  STORAGE_SECRET_KEY: {{ .Values.config.storageSecretKey | quote }}
  {{- end }}
